const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
const {pathToFileURL}=require('node:url');const path=require('node:path');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROME_PATH,headless:true});try{
 const p=await b.newPage({viewport:{width:568,height:320}});const errors=[];p.on('pageerror',e=>errors.push(e.message));
 const url=pathToFileURL(path.resolve(__dirname,'../index.html')).href;
 await p.goto(url);assert.equal(await p.locator('#continueGame').isDisabled(),true);
 await p.getByRole('button',{name:'はじめから',exact:true}).click();await p.waitForFunction(()=>Game.started);
 assert.equal(await p.evaluate(()=>localStorage.getItem(SAVE_KEY)),null);
 await p.getByRole('button',{name:'▶ ちょうさメモ',exact:true}).click();
 assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem(SAVE_KEY)).game.place),'職員室');
 await p.evaluate(()=>{Game.place='801教室';Game.inventory=['血の付いたカッター','赤いUSBメモリ'];Game.flags.bodyFound=true;Game.flags.usbRead=true;Game.flags.kimuraTestimony=true;Game.flags.accused=true;renderCommandList();});
 await p.addStyleTag({content:'body {padding-bottom:21px}'});
 assert.equal(await p.evaluate(()=>commands().scrollHeight<=commands().clientHeight),true);
 await p.getByRole('button',{name:'▶ ちょうさメモ',exact:true}).click();
 const saved=await p.evaluate(()=>localStorage.getItem(SAVE_KEY));
 await p.reload();assert.equal(await p.locator('#continueGame').isDisabled(),false);
 await p.getByRole('button',{name:'つづきから',exact:true}).click();await p.waitForFunction(()=>Game.started);
 assert.deepEqual(await p.evaluate(()=>({place:Game.place,inventory:Game.inventory,flags:Game.flags})),JSON.parse(saved).game);
 assert.equal(await p.evaluate(()=>CharacterSprites['関澤遼'].idle),'images/sekizawa_03.png');
 await p.reload();await p.getByRole('button',{name:'はじめから',exact:true}).click();await p.waitForFunction(()=>Game.started);
 assert.equal(await p.evaluate(()=>Game.place),'職員室');assert.equal(await p.evaluate(()=>Game.inventory.length),0);
 assert.equal(await p.evaluate(()=>localStorage.getItem(SAVE_KEY)),saved);
 await p.evaluate(()=>localStorage.setItem(SAVE_KEY,'broken'));await p.reload();assert.equal(await p.locator('#continueGame').isDisabled(),true);
 await p.getByRole('button',{name:'はじめから',exact:true}).click();await p.waitForFunction(()=>Game.started);
 await p.evaluate(()=>{Storage.prototype.setItem=()=>{throw Error('quota');};});
 await p.getByRole('button',{name:'▶ ちょうさメモ',exact:true}).click();await p.waitForFunction(()=>message().textContent.includes('保存できませんでした'));
 assert.deepEqual(errors,[]);console.log('PASS manual-only save, overwrite, reload/restore, sprite state, fresh start preserves save, invalid save, storage failure, nine commands');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
